// Generated by https://quicktype.io

export interface Question {
    question_id: number
    teks_pertanyaan: string
    answer: Answer[]
}

export interface Answer {
    answer_id: number
    teks_jawaban: string
}
